from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .agents import AgentReport
from .portfolio import PortfolioDecision


def render_markdown(
    inst_id: str,
    generated_at: str,
    reports: list[AgentReport],
    decision: PortfolioDecision,
) -> str:
    lines = [
        f"# {inst_id} 多智能体分析报告",
        "",
        f"生成时间：{generated_at}",
        "",
        "## 最终决策",
        "",
        f"- **Action**: `{decision.action}`",
        f"- **Confidence**: {decision.confidence}/100",
        f"- **Position Size**: {decision.position_size_pct}",
        f"- **Stop Loss**: {decision.stop_loss}",
        f"- **Take Profit**: {decision.take_profit}",
        f"- **Time Horizon**: {decision.time_horizon}",
        f"- **Generated By**: {decision.generated_by}",
        "",
        decision.summary,
        "",
        "### 理由",
        "",
    ]
    lines.extend(f"- {reason}" for reason in decision.reasons)
    lines.extend(["", "### 风险", ""])
    lines.extend(f"- {risk}" for risk in decision.risks)
    lines.extend(["", "## Agent 报告", ""])
    for report in reports:
        lines.extend(
            [
                f"### {report.title}",
                "",
                report.summary,
                "",
            ]
        )
        lines.extend(f"- {item}" for item in report.bullets)
        lines.append("")
    lines.extend(
        [
            "---",
            "",
            "本报告由自动化程序生成，仅供研究参考，不构成投资建议。",
        ]
    )
    return "\n".join(lines)


def write_report(
    reports_dir: Path,
    inst_id: str,
    generated_at: str,
    reports: list[AgentReport],
    decision: PortfolioDecision,
    state: dict[str, Any],
) -> tuple[Path, Path]:
    safe_name = inst_id.replace("/", "_").replace("-", "_").upper()
    target_dir = reports_dir / safe_name
    target_dir.mkdir(parents=True, exist_ok=True)
    file_stem = generated_at.replace(":", "").replace("-", "")
    markdown_path = target_dir / f"{file_stem}.md"
    json_path = target_dir / f"{file_stem}.json"
    markdown_path.write_text(
        render_markdown(inst_id, generated_at, reports, decision),
        encoding="utf-8",
    )
    payload = {
        "instrument": inst_id,
        "generated_at": generated_at,
        "decision": decision.to_dict(),
        "reports": [report.to_dict() for report in reports],
        "state": state,
    }
    json_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return markdown_path, json_path
